In [14]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\hp\appdata\roaming\python\python313\site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (2.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
%pip install matplotlib seaborn

Requirement already satisfied: matplotlib in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (2.5.1)
Requirement already satisfied: packaging>=20.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: tzdata in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
import sys
print(sys.executable)

C:\Users\Hp\AppData\Local\Python\pythoncore-3.14-64\python.exe

In [18]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
df= pd.read_csv(r"C:\Users\Hp\Downloads\Social_Network_Ads.csv")

In [20]:
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

In [8]:
df.sample(5)

     Age  EstimatedSalary  Purchased
274   57            26000          1
227   56           133000          1
317   35            55000          0
146   27            96000          1
355   60            34000          1

In [9]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
from sklearn.model_selection import train_test_split

X = df.drop('Purchased', axis=1)
y = df['Purchased']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=0
)

print(X_train.shape)
print(X_test.shape)

(280, 2)
(120, 2)

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
scaler.mean_

array([3.48927236e-17, 6.34413157e-17])

In [34]:
feature_names = df.drop('Purchased', axis=1).columns

X_train_scaled = pd.DataFrame(X_train_scaled, columns=feature_names)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=feature_names)

In [35]:
print(X_train_scaled.head())
print(X_train_scaled.describe())

        Age  EstimatedSalary
0 -1.163172        -1.584970
1  2.170181         0.930987
2  0.013305         1.220177
3  0.209385         1.075582
4  0.405465        -0.486047
                Age  EstimatedSalary
count  2.800000e+02     2.800000e+02
mean  -1.268826e-17     1.268826e-17
std    1.001791e+00     1.001791e+00
min   -1.947491e+00    -1.584970e+00
25%   -7.710131e-01    -7.752370e-01
50%   -8.473441e-02     2.003677e-02
75%    7.976239e-01     5.261201e-01
max    2.170181e+00     2.319101e+00